name: test&deploy

on:
  [push]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Starting Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: install modules
        run: npm install
      
      - name: build project
        run: npm run build
      
      - name: lint project
        run: npm run lint
      
      - name: test project
        run: npm run test
  build:
    runs-on: ubuntu-latest
    needs: tests
    steps:
      - uses: actions/checkout@v3
      - name: Build and push docker
        run: |
          DOCKER_NAME=messanger-app
          DOCKER_IMAGE=docker.pkg.github.com/provodnicc/${GITHUB_REPOSITORY##*/}/${DOCKER_NAME}:master
          docker login docker.pkg.github.com -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }}
          docker build -f Dockerfile --pull -t $DOCKER_IMAGE .
          docker push $DOCKER_IMAGE
      
      - name: deploy
        uses: satak/webrequest-action@master
        with:
          url: "http://admin.teeeest.xyz/api/webhooks/6a33374c-b3cc-4b4b-ab7d-f3fa48c58246"
          method: POST
