name: deploy

on:
  push:
    branches:
      - master
  

jobs:  
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build and push docker
        run: |
          DOCKER_NAME=messanger-app
          DOCKER_IMAGE=docker.pkg.github.com/provodnicc/${GITHUB_REPOSITORY##*/}/${DOCKER_NAME}:master
          docker login docker.pkg.github.com -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }}
          docker build -f Dockerfile --pull -t $DOCKER_IMAGE .
          docker push $DOCKER_IMAGE
      
      - name: deploy
        uses: satak/webrequest-action@master
        with:
          url: "https://admin.teeeest.xyz/api/webhooks/17eb84a5-1a51-4c84-880f-f5582985f9a9"
          method: POST
