name: github-actions
on: [push]
jobs:
  init:
    runs-on: ubuntu-latest
    strategy: 
      matrix: 
        node-version: [ 18.x ]
    steps:
      - uses: actions/checkout@v3
      
      - name: Starting Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: install modules
        run: npm install
      
      - name: build project
        run: npm run build
      
      - name: lint project
        run: npm run lint
      
      - name: test project
        run: npm run test
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: action/checkout@v3
      - name: Build and push docker
      run: |
        DOCKER_NAME=messanger-app
        DOCKER_IMAGE=docker.pkg.github.com/provodnicc/${GITHUB_REPOSITORY##*/}/${DOCKER_NAME}:${GITHUB_REF##*/}
        docker login docker.pkg.github.com -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }}
        docker build -f Dockerfile --pull -t $DOCKER_IMAGE .
        docker push $DOCKER_IMAGE